### ISSUE TITLE
How are we handling missing values? Please fill me in with useful links in here. :)

### ISSUE THREAD

**Issue by mhatreapurva** [mhatreapurva/EmployeeAttrition#1]

**Comment by avantidotpy** [comment]
Okay so, there can be two kinds of issues:
1. Values missing at random
2. Values missing not at random.

Here are some links that throw some light over these kinds of issues:
a. https://www.kaggle.com/dansbecker/handling-missing-values
b. https://heartbeat.fritz.ai/data-handling-scenarios-part-2-working-with-missing-values-in-a-dataset-34b758cfc9fa
c. https://towardsdatascience.com/data-cleaning-with-python-and-pandas-detecting-missing-values-3e9c6ebcf78b

**Comment by mhatreapurva** [comment]
Thank you, I am closing this issue now.
